language: cpp
compiler: gcc
sudo: required
dist: bionic
git:
  depth: 3

addons:
  apt:
    packages:
      - p7zip-full
      - ninja-build
      - libhunspell-dev
      - libgl1-mesa-dev
      - libgstreamer-plugins-base1.0-0
      - libpulse-mainloop-glib0
      - python3-pip
  homebrew:
    update: true
    packages:
      - p7zip
      - ninja
      - hunspell

env:
  global:
    - QT_VERSION=5.13.1
    - QTWEBKIT_BRANCH=5.212
    - QTWEBKIT_BUILD_NUMBER=1570144483
    - QT_INSTALL_DIR=~/Qt
    - QT_MODULES="qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel qtsvg qtxmlpatterns"
    - HOST_N_CORES=2
    - secure: BVQ+sHDicLY0tr9ECpn4UNU2lw0X6JaSSrJn6LgfZdoPd34fPSX2Sbx2y0TFJ9VLDX+8LOmOw1ZuNThF+OovonGHVCAmEJN+JRDCuyqgbYcwv/vpWLhwy4FtYc0oGIHHiof+V5afE9e4aReYSNHn8MlyVewc9Qx0xChrnjzAmi9r/szXnkY7JZFt8+cYXChbolxFYa4rJXATkuDmGwmmi2ROPSpmh/XWMIwH1Wmt9PoaZU4djlvlmt8RHNYa/BMejGZiaqDuzzdPjVki6e9CKuzZ5pVTvK5vHHNbrwkAU2vLMWpiDrfSBM89evZ3ujPNHe9zG1SlLBmeaWGayNIm5GXLScz7deMFu28cMXY0y+h2bZSPChqTqtNcfsBcou7ir/2HW572yem65UcVfXwE9KD8SsLKa1pJXzcY7MciWat0/QLILZuX2X4r9y5n2ZNNN8O7SXADjmAmmj/uKKTRML5UHGoE4lrk11fi02rlNi/Y6XApjBeFmZ3PIIHVpxqM4epHRMx6ioPGZBWJ2gc2rBLuDTYoyCvDpnxqiezcFrIhTnug/uxu0/f2tkhsSoWXzv3DnvA55yzMKbT6JWTJoQhrbA1/198vaH3+MixGfg6qEBXFyfrawWOCQuMS48QVtceZKxQUrPZ1a8kuAKPeApLVZCFGv8JiRIh+IdSwkL4=

before_deploy:
  - sed -ie "s|TRAVIS_BUILD_NUMBER|${TRAVIS_BUILD_NUMBER}|" bintray.json

deploy:
  provider: bintray
  user: annulen
  file: bintray.json
  edge: true # opt in to dpl v2
  on:
    condition: $DEPLOY = 1

after_deploy:
  - ./bintray_upload.sh qa-*.7z

matrix:
  include:
  - name: "macOS x86_64"
    os: osx
    osx_image: xcode10.1
    env:
      CMAKE_GENERATOR=Ninja
    install:
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} ${QT_MODULES} qtmacextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/clang_64"
      - export QT_QPA_PLATFORM_PLUGIN_PATH=$QTDIR/plugins
      - export PATH="$QTDIR/bin:$PATH"
      - ./install-qtwebkit MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64
    before_script:
      - du -hs $QTDIR
      - qmake -query
    script:
      - ./build-pyqt5.sh
      - ./build-otter.sh
      - ./build-phantomjs.sh
  - name: "VS 2017 x86"
    os: windows
    env:
      CMAKE_GENERATOR="Visual Studio 15 2017"
      QT_INSTALL_DIR=C:/Qt
      DEPLOY=1
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
      - gem install bundler
    install:
      - choco install jom
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win32_msvc2017 ${QT_MODULES} qtwinextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017"
      - export QT_QPA_PLATFORM_PLUGIN_PATH="$(cygpath -u $QTDIR/plugins)"
      - export PATH="$(cygpath -u ${QTDIR})/bin:$PATH"
      - ./install-qtwebkit Windows_10-MSVC2017-Windows-Windows_10-X86
    before_script:
      - du -hs $QTDIR
      - qmake -query
    script:
      - ./build-otter.sh
      - VS_ARCH=x86 ./build-phantomjs-vs.bat
      - VS_ARCH=x86 ./build-examples-vs.bat
      - ./create-qa-archive.sh qa-${TRAVIS_JOB_NUMBER}-msvc2017-x86.7z
  - name: "VS 2017 x86_64"
    os: windows
    env:
      CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
      QT_INSTALL_DIR=C:/Qt
      DEPLOY=1
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
      - gem install bundler
    install:
      - choco install jom
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win64_msvc2017_64 ${QT_MODULES} qtwinextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017_64"
      - export QT_QPA_PLATFORM_PLUGIN_PATH="$(cygpath -u $QTDIR/plugins)"
      - export PATH="$(cygpath -u ${QTDIR})/bin:$PATH"
      - ./install-qtwebkit Windows_10-MSVC2017-Windows-Windows_10-X86_64
    before_script:
      - du -hs $QTDIR
      - qmake -query
    script:
      - ./build-otter.sh
      - VS_ARCH=amd64 ./build-phantomjs-vs.bat
      - VS_ARCH=amd64 ./build-examples-vs.bat
      - ./create-qa-archive.sh qa-${TRAVIS_JOB_NUMBER}-msvc2017-x86_64.7z
  - name: "MinGW 7.3 x86"
    os: windows
    env:
      CMAKE_GENERATOR="MSYS Makefiles"
      CMAKE_ARGS="-DCMAKE_MAKE_PROGRAM=mingw32-make"
      QT_INSTALL_DIR=C:/Qt
      MAKE=mingw32-make
      DEPLOY=1
    before_install:
      - powershell.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File windows_setup.ps1
      - gem install bundler
    install:
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win32_mingw73 ${QT_MODULES} qtwinextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/mingw73_32"
      - export QT_QPA_PLATFORM_PLUGIN_PATH="$(cygpath -u $QTDIR/plugins)"
      - export PATH="$(cygpath -u ${QTDIR})/bin:$PATH"
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version 7.3.0 win32_mingw730
      - export PATH="$(cygpath -u ${QT_INSTALL_DIR})/Tools/mingw730_32/bin:$PATH"
      - ./install-qtwebkit Windows_7-Mingw73-Windows-Windows_7-X86
    before_script:
      - du -hs $QTDIR
      - qmake -query
      - g++ -v
      - mingw32-make --version
    script:
      - ./build-otter.sh
      - ./build-phantomjs.sh
      - ./build-examples.sh
      - ./create-qa-archive.sh qa-${TRAVIS_JOB_NUMBER}-mingw73-x86.7z
  - name: "Linux x86_64"
    os: linux
    env:
      CMAKE_GENERATOR=Ninja
      DEPLOY=1
    install:
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} ${QT_MODULES} icu
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64"
      - export QT_QPA_PLATFORM_PLUGIN_PATH=$QTDIR/plugins
      - export PATH="$QTDIR/bin:$PATH"
      - export LD_LIBRARY_PATH=$QTDIR/lib
      - ./install-qtwebkit RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64
    before_script:
      - du -hs $QTDIR
      - qmake -query
    script:
      - ./build-pyqt5.sh
      - ./build-otter.sh
      - ./build-phantomjs.sh
      - ./build-examples.sh
      - ./create-qa-archive.sh qa-${TRAVIS_JOB_NUMBER}-linux-x86_64.7z
