language: cpp
compiler: gcc
sudo: required
dist: bionic
git:
  depth: 3

addons:
  apt:
    packages:
      - p7zip-full
      - ninja-build
      - libhunspell-dev
      - libgl1-mesa-dev
      - libgstreamer-plugins-base1.0-0
      - libpulse-mainloop-glib0
  homebrew:
    update: true
    packages:
      - p7zip
      - ninja
      - hunspell

env:
  global:
    QT_VERSION=5.13.0
    QT_INSTALL_DIR=~/Qt
    QT_MODULES="qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel qtsvg"

matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    install:
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} ${QT_MODULES} qtmacextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/clang_64"
      - ./install-qtwebkit
    before_script:
      - du -hs $QTDIR
      - $QTDIR/bin/qmake -query
      - export CMAKE_ARGS="-G Ninja"
  - os: windows
    env:
      QT_INSTALL_DIR=C:/Qt

    before_install:
      # Disable unnecessary background services which tend to consume
      # a lot of resources
      - powershell -Command 'Set-MpPreference -DisableRealtimeMonitoring $true'
      - powershell -Command 'Set-MpPreference -DisableArchiveScanning $true'
      - powershell -Command 'Set-MpPreference -DisableBehaviorMonitoring $true'
      - powershell -Command 'sc.exe config TrustedInstaller start=disabled; sc.exe stop TrustedInstaller'
      - powershell -Command 'sc.exe config wuauserv start=disabled; sc.exe stop wuauserv'
      - powershell -Command 'Add-MpPreference -ExclusionPath C:\'
      - powershell -Command 'Add-MpPreference -ExclusionProcess cmake.exe'
      - powershell -Command 'Add-MpPreference -ExclusionProcess cl.exe'
      - powershell -Command 'Add-MpPreference -ExclusionProcess link.exe'
    install:
      - choco install 7zip.commandline ninja
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win32_msvc2017 ${QT_MODULES} qtwinextras
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017"
      - ./install-qtwebkit
    before_script:
      - du -hs $QTDIR
      - $QTDIR/bin/qmake -query
  - os: linux
    install:
      - 3rdparty/install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} ${QT_MODULES} icu
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64"
      - ./install-qtwebkit
    before_script:
      - du -hs $QTDIR
      - $QTDIR/bin/qmake -query
      - export CMAKE_ARGS="-G Ninja"

script:
  - git clone --depth 1 https://github.com/annulen/otter-browser.git -b getCreationTime
  - mkdir otter-browser-build
  - cmake -Botter-browser-build -Hotter-browser -DCMAKE_PREFIX_PATH=$QTDIR $CMAKE_ARGS
  - cmake --build otter-browser-build --config Release
