language: cpp
compiler: gcc
sudo: required
dist: bionic
git:
  depth: 3

addons:
  apt:
    packages:
      - p7zip-full
      - ninja-build
      - libhunspell-dev
      - libgl1-mesa-dev
      - libgstreamer-plugins-base1.0-0
      - libpulse-mainloop-glib0
  homebrew:
    update: true
    packages:
      - p7zip
      - ninja
      - hunspell

env:
  global:
    QT_VERSION=5.13.0
    QT_INSTALL_DIR=~/Qt

matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    install:
      - ./install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/clang_64"
      - ./install-qtwebkit
    before_script:
      - $QTDIR/bin/qmake -query
      - export CMAKE_ARGS="-G Ninja"
      - find $QTDIR -name '*.dylib*' | sort
      - find $QTDIR -name 'QtWeb*' | sort
      - find $QTDIR -maxdepth 3 | sort
      - du -hs $QTDIR
  - os: windows
    env:
      QT_INSTALL_DIR=C:/Qt

    before_install:
      # Disable unnecessary background services which tend to consume
      # a lot of resources
      - powershell -Command 'Set-MpPreference -DisableRealtimeMonitoring $true'
      - powershell -Command 'Set-MpPreference -DisableArchiveScanning $true'
      - powershell -Command 'Set-MpPreference -DisableBehaviorMonitoring $true'
      - powershell -Command 'sc.exe config TrustedInstaller start=disabled; sc.exe stop TrustedInstaller'
      - powershell -Command 'sc.exe config wuauserv start=disabled; sc.exe stop wuauserv'
      - powershell -Command 'Add-MpPreference -ExclusionPath C:\'
      - powershell -Command 'Add-MpPreference -ExclusionProcess cmake.exe'
      - powershell -Command 'Add-MpPreference -ExclusionProcess cl.exe'
      - powershell -Command 'Add-MpPreference -ExclusionProcess link.exe'
    install:
      - choco install 7zip.commandline ninja
      - ./install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} --toolchain win64_msvc2017_64 qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/msvc2017_64"
      - ./install-qtwebkit
    before_script:
      - find $QTDIR -name '*.dll*' | sort
      - find $QTDIR -name 'QtWeb*' | sort
      - find $QTDIR -maxdepth 3 | sort
      - du -hs $QTDIR
  - os: linux
    install:
      - ./install-qt.sh -d ${QT_INSTALL_DIR} --version ${QT_VERSION} qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel
      - export QTDIR="${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64"
      - ./install-qtwebkit
    before_script:
      - export CMAKE_ARGS="-G Ninja"
      - find $QTDIR -name '*.so*' | sort
      - find $QTDIR -name 'QtWeb*' | sort
      - find $QTDIR -maxdepth 3 | sort
      - du -hs $QTDIR

script:
  - git clone --depth 1 https://github.com/OtterBrowser/otter-browser.git
  - mkdir otter-browser-build
  - cmake -Botter-browser-build -Hotter-browser -DQt5_DIR=$QTDIR/lib/cmake/Qt5 $CMAKE_ARGS
  - cmake --build otter-browser-build --config Release
